version: '3.7'


services:
  postgres:
    image: postgres:latest
    container_name: blog_postgres
    ports:
      - "5432:5432"

  composer:
    image: prooph/composer:7.3
    container_name: blog_composer
    volumes:
      - ./blog:/blog
    command: composer install
    working_dir: /blog

  redis:
    image: redis:latest
    container_name: blog_redis

  nginxssl:
    image: rodrigodiez/nginx-ssl-localhost
    container_name: blog_nginxssl
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./blog:/blog
      - ./sitessl.conf:/etc/nginx/conf.d/sitessl.conf


  blog_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog_app
    env_file: ./blog/.env
    expose:
      - "9000"
    volumes:
      - ./blog:/blog
    working_dir: /blog
    restart: always
    links:
      - postgres
      - nginxssl